class CustomName {
  final String name;
  final String meaning;

  const CustomName({required this.name, required this.meaning});
}

const List<CustomName> customNames = [
  CustomName(name: "Aiden", meaning: "Little fire (Irish)"),
  CustomName(name: "Sophia", meaning: "Wisdom (Greek)"),
  CustomName(name: "Liam", meaning: "Strong-willed warrior (Irish)"),
  CustomName(name: "Isabella", meaning: "Devoted to God (Hebrew)"),
  CustomName(name: "Noah", meaning: "Rest, comfort (Hebrew)"),
  CustomName(name: "Mila", meaning: "Gracious, dear (Slavic)"),
  CustomName(name: "Ethan", meaning: "Strong, firm (Hebrew)"),
  CustomName(name: "Amara", meaning: "Eternal, unfading (Latin/Igbo)"),
  CustomName(name: "Elijah", meaning: "My God is Yahweh (Hebrew)"),
  CustomName(name: "Aria", meaning: "Air, melody (Italian)"),
  CustomName(name: "Lucas", meaning: "Light, illumination (Latin)"),
  CustomName(name: "Layla", meaning: "Night, dark beauty (Arabic)"),
  CustomName(name: "James", meaning: "Supplanter (Hebrew)"),
  CustomName(name: "Ava", meaning: "Bird, life (Latin)"),
  CustomName(name: "Alexander", meaning: "Defender of men (Greek)"),
  CustomName(name: "Zara", meaning: "Princess, flower (Arabic/Hebrew)"),
  CustomName(name: "Benjamin", meaning: "Son of the right hand (Hebrew)"),
  CustomName(name: "Maya", meaning: "Illusion, water (Sanskrit/Hebrew)"),
  CustomName(name: "Daniel", meaning: "God is my judge (Hebrew)"),
  CustomName(name: "Chloe", meaning: "Blooming, fertility (Greek)"),
  CustomName(name: "Gabriel", meaning: "God is my strength (Hebrew)"),
  CustomName(name: "Nova", meaning: "New, star (Latin)"),
  CustomName(name: "Oliver", meaning: "Olive tree, peace (Latin)"),
  CustomName(name: "Amelia", meaning: "Industrious, striving (Germanic)"),
  CustomName(name: "William", meaning: "Resolute protector (Germanic)"),
  CustomName(name: "Elena", meaning: "Bright, shining light (Greek)"),
  CustomName(name: "Michael", meaning: "Who is like God? (Hebrew)"),
  CustomName(name: "Aurora", meaning: "Dawn, new beginning (Latin)"),
  CustomName(name: "Henry", meaning: "Ruler of the home (Germanic)"),
  CustomName(name: "Ivy", meaning: "Faithfulness, plant symbol (English)"),
  CustomName(name: "Samuel", meaning: "Heard by God (Hebrew)"),
  CustomName(name: "Clara", meaning: "Bright, clear (Latin)"),
  CustomName(name: "David", meaning: "Beloved (Hebrew)"),
  CustomName(name: "Freya", meaning: "Noble lady, goddess of love (Norse)"),
  CustomName(name: "Matthew", meaning: "Gift of God (Hebrew)"),
  CustomName(name: "Esme", meaning: "Esteemed, beloved (French)"),
  CustomName(name: "Jack", meaning: "God is gracious (Hebrew)"),
  CustomName(name: "Nora", meaning: "Honor, light (Latin/Irish)"),
  CustomName(name: "Joseph", meaning: "God will increase (Hebrew)"),
  CustomName(name: "Luna", meaning: "Moon (Latin)"),
  CustomName(name: "Andrew", meaning: "Manly, brave (Greek)"),
  CustomName(name: "Hazel", meaning: "Hazel tree, wisdom (English)"),
  CustomName(name: "Leo", meaning: "Lion, brave (Latin)"),
  CustomName(name: "Stella", meaning: "Star (Latin)"),
  CustomName(name: "Sebastian", meaning: "Venerable, revered (Greek)"),
  CustomName(name: "Ruby", meaning: "Precious red gemstone (Latin)"),
  CustomName(name: "Nathan", meaning: "He gave (Hebrew)"),
  CustomName(name: "Evelyn", meaning: "Desired, wished for (English)"),
  CustomName(name: "Caleb", meaning: "Faithful, wholehearted (Hebrew)"),
  CustomName(name: "Iris", meaning: "Rainbow, messenger (Greek)"),
  CustomName(name: "Isaac", meaning: "He will laugh (Hebrew)"),
  CustomName(name: "Aurélie", meaning: "Golden, shining (Latin/French)"),
  CustomName(name: "Owen", meaning: "Noble-born, young warrior (Welsh)"),
  CustomName(name: "Sienna", meaning: "Reddish-brown, from Siena (Italian)"),
  CustomName(name: "Julian", meaning: "Youthful, downy (Latin)"),
  CustomName(name: "Dahlia", meaning: "Flower, elegance (Scandinavian)"),
  CustomName(name: "Elias", meaning: "My God is Yahweh (Greek/Hebrew)"),
  CustomName(name: "Lydia", meaning: "From Lydia (Greek region)"),
  CustomName(name: "Charles", meaning: "Free man (Germanic)"),
  CustomName(name: "Anya", meaning: "Grace, favor (Russian/Hebrew)"),
  CustomName(name: "Thomas", meaning: "Twin (Aramaic)"),
  CustomName(name: "Amira", meaning: "Princess, leader (Arabic/Hebrew)"),
  CustomName(name: "Isaiah", meaning: "God is salvation (Hebrew)"),
  CustomName(name: "Selene", meaning: "Moon goddess (Greek)"),
  CustomName(name: "Ezekiel", meaning: "God strengthens (Hebrew)"),
  CustomName(name: "Maeve", meaning: "She who intoxicates (Irish)"),
  CustomName(name: "Silas", meaning: "Man of the forest (Latin)"),
  CustomName(name: "Daphne", meaning: "Laurel tree, victory (Greek)"),
  CustomName(name: "Miles", meaning: "Soldier, merciful (Latin)"),
  CustomName(name: "Valentina", meaning: "Strong, healthy (Latin)"),
  CustomName(name: "Aaron", meaning: "Exalted, strong (Hebrew)"),
  CustomName(name: "Leila", meaning: "Night, beauty (Arabic)"),
  CustomName(name: "Finn", meaning: "Fair, white (Irish)"),
  CustomName(name: "Camila", meaning: "Young ceremonial attendant (Latin)"),
  CustomName(name: "Jason", meaning: "Healer (Greek)"),
  CustomName(name: "Elsa", meaning: "Pledged to God (Germanic)"),
  CustomName(name: "Adam", meaning: "Man, earth (Hebrew)"),
  CustomName(name: "Naomi", meaning: "Pleasantness, delight (Hebrew)"),
  CustomName(name: "Patrick", meaning: "Noble, patrician (Latin)"),
  CustomName(name: "Liora", meaning: "Light, my light (Hebrew)"),
  CustomName(name: "Victor", meaning: "Conqueror, victor (Latin)"),
  CustomName(name: "Serena", meaning: "Calm, serene (Latin)"),
  CustomName(name: "Simon", meaning: "He has heard (Hebrew)"),
  CustomName(name: "Alina", meaning: "Bright, beautiful (Slavic)"),
  CustomName(name: "George", meaning: "Farmer, earthworker (Greek)"),
  CustomName(name: "Mira", meaning: "Peace, wonderful (Slavic/Latin)"),
  CustomName(name: "Peter", meaning: "Rock, stone (Greek)"),
  CustomName(name: "Helena", meaning: "Light, torch (Greek)"),
  CustomName(name: "Anthony", meaning: "Priceless one (Latin)"),
  CustomName(name: "Celeste", meaning: "Heavenly, celestial (Latin)"),
  CustomName(name: "Arthur", meaning: "Bear king, noble (Celtic)"),
  CustomName(name: "Aisha", meaning: "Alive, prosperous (Arabic)"),
  CustomName(name: "Marcus", meaning: "Dedicated to Mars (Latin)"),
  CustomName(name: "Fatima", meaning: "Captivating, one who abstains (Arabic)"),
  CustomName(name: "Philip", meaning: "Lover of horses (Greek)"),
  CustomName(name: "Zaynab", meaning: "Fragrant flower (Arabic)"),
  CustomName(name: "Theodore", meaning: "Gift of God (Greek)"),
  CustomName(name: "Yara", meaning: "Small butterfly (Arabic/Brazilian)"),
  CustomName(name: "Christopher", meaning: "Bearer of Christ (Greek)"),
  CustomName(name: "Anastasia", meaning: "Resurrection (Greek)"),
  CustomName(name: "Jonathan", meaning: "God has given (Hebrew)"),
  CustomName(name: "Salma", meaning: "Peace, safety (Arabic)"),
  CustomName(name: "Raphael", meaning: "God heals (Hebrew)"),
  CustomName(name: "Khadija", meaning: "Premature child, first wife of Prophet Muhammad (Arabic)"),
];
